name: Test-automation
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v3
      - name: Install Python
        uses: setup-python@v5
        with:
          pythion-version:'3.13'
      - name: Install a Python Package
        run:  pip install streamlit
      - name: Run the streamlit application
        run: streamlit run test.py
      - name: End Script
        run: echo "Process Ran Successfully"